// Code generated by sqlc. DO NOT EDIT.

package models

import (
	"database/sql"
	"time"
)

type Plmn struct {
	ID          int64
	Mcc         string
	Mnc         string
	Iso         string
	Country     string
	CountryCode sql.NullString
	Network     string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
