// Code generated by sqlc. DO NOT EDIT.
// source: query.sql

package models

import (
	"context"
	"database/sql"
	"time"
)

const getPlmn = `-- name: GetPlmn :one
SELECT id, mcc, mnc, iso, country, country_code, network, created_at, updated_at FROM plmn
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPlmn(ctx context.Context, id int64) (Plmn, error) {
	row := q.db.QueryRowContext(ctx, getPlmn, id)
	var i Plmn
	err := row.Scan(
		&i.ID,
		&i.Mcc,
		&i.Mnc,
		&i.Iso,
		&i.Country,
		&i.CountryCode,
		&i.Network,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlmn = `-- name: ListPlmn :many
SELECT id, mcc, mnc, iso, country, country_code, network, created_at, updated_at FROM plmn
`

func (q *Queries) ListPlmn(ctx context.Context) ([]Plmn, error) {
	rows, err := q.db.QueryContext(ctx, listPlmn)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plmn
	for rows.Next() {
		var i Plmn
		if err := rows.Scan(
			&i.ID,
			&i.Mcc,
			&i.Mnc,
			&i.Iso,
			&i.Country,
			&i.CountryCode,
			&i.Network,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlmn = `-- name: UpsertPlmn :execresult
INSERT INTO plmn (
	mcc,
  mnc,
  iso,
  country,
  country_code,
  network,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?
) ON DUPLICATE KEY
  UPDATE
	mcc = ?,
  mnc = ?,
  iso = ?,
  country = ?,
  country_code = ?,
  network = ?,
  updated_at = ?
`

type UpsertPlmnParams struct {
	Mcc           string
	Mnc           string
	Iso           string
	Country       string
	CountryCode   sql.NullString
	Network       string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Mcc_2         string
	Mnc_2         string
	Iso_2         string
	Country_2     string
	CountryCode_2 sql.NullString
	Network_2     string
	UpdatedAt_2   time.Time
}

func (q *Queries) UpsertPlmn(ctx context.Context, arg UpsertPlmnParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, upsertPlmn,
		arg.Mcc,
		arg.Mnc,
		arg.Iso,
		arg.Country,
		arg.CountryCode,
		arg.Network,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Mcc_2,
		arg.Mnc_2,
		arg.Iso_2,
		arg.Country_2,
		arg.CountryCode_2,
		arg.Network_2,
		arg.UpdatedAt_2,
	)
}
